# Generated by Django 5.0.3 on 2024-04-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_job_post_job_title_alter_ml_record_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ml_record',
            old_name='ch_score',
            new_name='calinski_harabasz_score',
        ),
        migrations.RenameField(
            model_name='ml_record',
            old_name='sh_score',
            new_name='silhouette_score',
        ),
    ]
