# Generated by Django 5.0.3 on 2024-04-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_ch_score_ml_record_calinski_harabasz_score_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ML_record',
            new_name='cluster_records',
        ),
    ]
