# Generated by Django 5.0.3 on 2024-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_cluster_records_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster_records',
            name='calinski_harabasz_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cluster_records',
            name='silhouette_score',
            field=models.FloatField(),
        ),
    ]
