# Generated by Django 5.0.3 on 2024-04-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_cluster_records_calinski_harabasz_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='globals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_thread_running', models.BooleanField(default=False)),
                ('number_of_tests', models.IntegerField(default=True)),
            ],
        ),
    ]
