# Generated by Django 5.0.3 on 2024-04-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_globals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globals',
            old_name='test_thread_running',
            new_name='testing_thread_running',
        ),
    ]
