# Generated by Django 5.0.3 on 2024-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_number_of_tests_globals_number_of_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globals',
            name='number_of_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='globals',
            name='testing_thread_running',
            field=models.IntegerField(default=False),
        ),
    ]
